module.exports = {
    DEPOSIT: 'DEPOSIT',
    WITHDRAW: 'WITHDRAW',
    REFERRAL_DEPOSIT: 'REFERRAL_DEPOSIT',
    TAKE_ORDER: 'TAKE_ORDER',
    CANCEL_ORDER: 'CANCEL_ORDER',
    REFERRAL_BALANCE: 'REFERRAL_BALANCE',
};
